apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: toggle-master
  labels:
    app: analytics-service
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/<ACCOUNT_ID>/toggle-events-queue"
  AWS_DYNAMODB_TABLE: "toggle-analytics"
  AWS_ENDPOINT_URL: ""
