apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: toggle-master
  labels:
    app: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: <ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: PORT
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: AWS_REGION
            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: AWS_SQS_URL
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: AWS_DYNAMODB_TABLE
            - name: AWS_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: AWS_ENDPOINT_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
