apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: toggle-master
  labels:
    app: analytics-service
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
