apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: analytics-service
  labels:
    app: analytics-service
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "<ACCOUNT_ID>"
  AWS_SECRET_ACCESS_KEY: "<SECRET_ACCESS_KEY>"
  AWS_SESSION_TOKEN: "<SESSION_TOKEN>"
