apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
  labels:
    app: auth-service
type: Opaque
data:
  DATABASE_URL: "<POSTGRESQL_CONNECTION_STRING_BASE64_ENCODED>"
  MASTER_KEY: "<MASTER_KEY>"