apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: targeting-service
  labels:
    app: targeting-service
type: Opaque
data:
  DATABASE_URL: "<POSTGRESQL_CONNECTION_STRING_BASE64_ENCODED>"
