apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: evaluation-service
  labels:
    app: evaluation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: <ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/evaluation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: evaluation-service-secret
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: PORT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: REDIS_URL
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: FLAG_SERVICE_URL
            - name: TARGETING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: TARGETING_SERVICE_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_REGION
            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_SQS_URL
            - name: AWS_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_ENDPOINT_URL
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-secret
                  key: SERVICE_API_KEY
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "600m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
