apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: toggle-master
  labels:
    app: evaluation-service
type: Opaque
data:
  SERVICE_API_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
