apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: evaluation-service
  labels:
    app: evaluation-service
type: Opaque
data:
  SERVICE_API_KEY: ""
  AWS_ACCESS_KEY_ID: "<ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<SECRET_ACCESS_KEY>"
  AWS_SESSION_TOKEN: "<SESSION_TOKEN>"
