name: Lint Evaluation Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'local/services/evaluation-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'local/services/evaluation-service/**'
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint-go.yml
    with:
      service_path: local/services/evaluation-service
      go_version: '1.23'
